### ISSUE TITLE
New Round Tracking

### ISSUE THREAD

**Issue by dalesaul** [dalesaul/Frolf-App#3]
**Story**
As a user has already selected course type and wants to start tracking their round scores, from the grid view of holes, I should be able to click on each hole and input score for the hole and submit score for hole

**Acceptance Criteria**

Given a user wants to start tracking their round score After a user has selected course from #2 the user should be presented with grid view of cards for each hole of the course
Given the user wants to edit par for the hole there should be an affordance to do so
Given the user wants to record their score for the hole they should be provided with an input form that allows only numerical input or tick counter
Given a user submits score for a hole, score is added to hole score and tied to roundId and holeId
When the user submits score they are redirected back to the grid view of holes for course
Given the user has finished playing there should be an affordance to finalize the round. 
When the user finalizes round they are redirected to the Round History page

**Progress**

- [x] Create grid view with cards for each hole

- [x] clicking on card should open hole detail score card

- [x] Hole detail score cards should include: Par w/ edit affordance,  score input, and submit button

- [x] when score submitted, hole score saved

- [x] when score submitted, redirect to grid overview

- [x] Finalize round affordance w/ redirect to Round History page
